### ISSUE TITLE
Question regarding services

### ISSUE THREAD

**Issue by Zweer** [hybris/elasticsearch-boshrelease#1]
Hi,

first of all nice work, I'm trying to deploy all your repos in my home bosh-lite installation...

Just a question: how can your deployments be configured to be cloud foundry services? Or there is something else I'm not considering??

Sorry for the newbie question, but I'm trying to familiarize with bosh and cloud foundry and trying to understand better all the components of this infrastructure...

Thanks,
Bye

**Comment by joek** [comment]
Hi,
there is no service broker for CF available. If you like to connect your CF app to ES you have to create an custom service (cf cups) or you are using std. environment variables. 

The bosh release is a simple elastic search cluster installation no multitanancy or authentication / authorization is available.

**Comment by Zweer** [comment]
Ok, thanks!!! So if I have to use that I have to connect via the ip of the vm? DO you know if there is a "basic" custom service "template" out there?

**Comment by joek** [comment]
You can create a custom service:

```
$ cf cups -h
NAME:
   create-user-provided-service - Make a user-provided service instance available to cf apps

USAGE:
   cf create-user-provided-service SERVICE_INSTANCE [-p CREDENTIALS] [-l SYSLOG-DRAIN-URL]

   Pass comma separated credential parameter names to enable interactive mode:
   cf create-user-provided-service SERVICE_INSTANCE -p "comma, separated, parameter, names"

   Pass credential parameters as JSON to create a service non-interactively:
   cf create-user-provided-service SERVICE_INSTANCE -p '{"name":"value","name":"value"}'

EXAMPLE 
      cf create-user-provided-service my-db-mine -p "username, password"
      cf create-user-provided-service my-drain-service -l syslog://example.com

   Linux/Mac:
      cf create-user-provided-service my-db-mine -p '{"username":"admin","password":"pa55woRD"}'

   Windows Command Line
      cf create-user-provided-service my-db-mine -p "{\"username\":\"admin\",\"password\":\"pa55woRD\"}"

   Windows PowerShell
      cf create-user-provided-service my-db-mine -p '{\"username\":\"admin\",\"password\":\"pa55woRD\"}'


ALIAS:
   cups

OPTIONS:
   -p       Credentials
   -l       Syslog Drain Url

```

There is a static service broker too https://github.com/cloudfoundry-community/worlds-simplest-service-broker

**Comment by Zweer** [comment]
Ok, many thanks for the repo link, but how can I create a custom service with "cups"? I mean, I have es and I want it to be a service for other apps... Is it possible to use it as a service with "cups" or I have to write "external" logics that allow me to use it? With "cups" it seems I only need some credentials (which credentials?) to setup a service... What am I missing?

Thanks for the patience!!

**Comment by joek** [comment]
First you can try to connect to elastic search from your local box. ES is listening on port 9200. With bosh vms you can findout the IP of the VM / Warden container of ES. If this is working you could use a simple cloud foundry environment variable to setup connection to ES or you could create a a user provided service. Then you add the connection details into the json hash. The hash can look how every you like. You could user for example: {"url":"http://x.x.x.x:9200"}

**Comment by Zweer** [comment]
Perfect, thanks a lot!! Really kind of you!!!
